#!/bin/bash
#
# Cretae a bunch of trace files using the generator with
# different parameter sets
#

#
# User-specified parameters
#
# PARAMS -- one trace will be generated for each parameter
#           set specified here
# 
# NAMES  -- name for the trace file generated by the
#           corresponding entry in PARAMS (optional)
#           If a name is not specified, it will be test.n.trace
#           where n is a unique number over all the traces generated

PARAMS=(
    # -l <trace-length> -t <datatype> -b <bias> -d <avg-delay> -s <stddev-delay>
    "-l 10     -t int  -b insert  -d 200 -s 50"
    "-l 20     -t int -b insert -d 200 -s 50"
    "-l 40     -t int  -b lookup  -d 200 -s 50"
    "-l 80     -t int  -b lookup  -d 200 -s 50"
    "-l 160     -t int  -b lookup  -d 200 -s 50"
    "-l 320     -t int  -b lookup  -d 200 -s 50"
    "-l 640     -t int  -b lookup  -d 200 -s 50"
    "-l 1280     -t int  -b lookup  -d 200 -s 50"
    "-l 2560     -t int  -b lookup  -d 200 -s 50"
    "-l 5120     -t int  -b lookup  -d 200 -s 50"
    "-l 10240     -t int  -b lookup  -d 200 -s 50"
    "-l 20480     -t int  -b lookup  -d 200 -s 50"
    "-l 40960     -t int  -b lookup  -d 200 -s 50"
    "-l 81920     -t int  -b lookup  -d 200 -s 50"
)

NAMES=(
    "trace0"
    "trace1"
    "trace2"
    "trace3"
    "trace4"
    "trace5"
    "trace6"
    "trace7"
    "trace8"
    "trace9"
    "trace10"
    "trace11"
    "trace12"
    "trace13"
)


#
# Main generator script
#

TRACEDIR=traces
COUNTER=0

function usage() {
    echo "usage: $0 <output-dir>"
    echo "  <output-dir> : subdirectory to be created under the main traces/"
    echo "                 directory, which will hold the generated traces"
    echo "                 The program will exit with an error if <output-dir>"
    echo "                 already exists."
    echo ""
}

if [[ $# < 1 ]] ; then
    usage
    exit 1
fi

if [ -d $TRACEDIR/$1 ] ; then
    echo "Output destination $TRACEDIR/$1 already exists!  Aborting."
    exit 2
else
    mkdir -p $TRACEDIR/$1
fi

for paramset in "${PARAMS[@]}"; do
    if [[ $COUNTER -lt ${#NAMES[@]} ]]; then
        name=${NAMES[$COUNTER]}
    else
        name="test.$COUNTER.trace"
    fi
    COUNTER=$(($COUNTER + 1))
    scripts/tracegen.py $paramset > $TRACEDIR/$1/$name
done
